version: '3'

includes:
  github:
    taskfile: github.Taskfile.yml
    dir: .

  edge:
    taskfile: backend/edge/Taskfile.yml
    dir: backend/edge

  gradle:
    taskfile: gradle.Taskfile.yml
    dir: .

tasks:
  fixAll:
    desc: Apply all automatic fixes
    deps:
      - github:fixLint
      - edge:fixFormatting
      - edge:fixLint
      - gradle:fixFormatting
