[versions]
# The first line supporting JDK 25
detekt = "2.0.0-alpha.6"
jib = "3.5.4"
kotlin = "2.4.10"
ksp = "2.3.12"
ktfmt = "0.27.0"
micronaut-plugin = "5.0.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronaut-plugin" }
