name: Check PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-gh-workflows:
    name: GitHub workflows
    uses: ./.github/workflows/check-gh-workflows.yml

  check-edge:
    name: Edge
    uses: ./.github/workflows/check-edge.yml

  check-backend:
    name: Backend
    uses: ./.github/workflows/check-backend.yml
